build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
  php:
    excluded_dependencies:
      - 'vendor/*'
      - 'bedita-app/vendor/*'

filter:
  paths:
    - 'bedita-app/*'
  dependency_paths:
    - 'vendor/*'
    - 'bedita-app/vendor/*'
