build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
  php: true

filter:
  paths:
    - 'bedita-app/'
  excluded_paths:
    - 'vendor/'
    - 'bedita-app/tmp/'
    - 'bedita-app/vendor/'