language: php

dist: trusty
sudo: required

services:
  - memcached
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - RUN_TESTS=1

jobs:
  fast_finish: true

  include:
    - stage: minimal
      php: 5.6
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.0
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: minimal
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: minimal
      php: hhvm
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: RUN_CS=1 RUN_TESTS=0

    - stage: complete
      php: 5.6
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 5.6
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.1
      env: "DB=mysql DB_VERSION=5.6 db_dsn='mysql://root@localhost/bedita_test'"
      services:
        - memcached
        - mysql
        - redis-server
      addons: {}
    - stage: complete
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.5 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
      addons:
        postgresql: "9.5"
    - stage: complete
      php: hhvm
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.1
      env: RUN_PHPSTAN=1 RUN_TESTS=0

    - stage: deploy
      php: 7.1
      env: RUN_TESTS=0
      addons: {}
      deploy:
        provider: heroku
        app: bedita4
        skip_cleanup: true
        run:
          - "bin/cake migrations migrate -p BEdita/Core"
          - "bin/cake cache clear_all"
        api_key:
          secure: IoV+GK7hyX8/uWmuF7xuc+4SM0a9mCmKAckOTJ+LZj1zpzXRE8LkPXm5GnuYoO/ambRoZkORDwclrXMsloY3TJMFvJxG6UnOlKANBzwKankZK6vWv0O3Jni4TtbW48OShH7yj6iCS7uvwPFrA76c21qlLBp34QAFJO0y73lS+sY=
        before_script:
          - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
          - composer install --prefer-dist --no-interaction --no-dev
        on:
          all_branches: true
#          branch:
#            - 4-cactus
#          repo: bedita/bedita

  allow_failures:
    - php: 7.1
      env: RUN_PHPSTAN=1 RUN_TESTS=0

before_script:
  - |
    if [ "$DB" = 'mysql' ] && [ "$DB_VERSION" = '5.7' ]; then
      echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
      wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
      sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
      sudo apt-get update -q
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" mysql-server
      sudo mysql_upgrade
    fi

  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
  - composer install --prefer-dist --no-interaction

  - if [ "$DB" = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE bedita_test;'; mysql -u root -e 'SHOW DATABASES;'; fi
  - if [ "$DB" = 'pgsql' ]; then psql -c 'CREATE DATABASE bedita_test;' -U postgres; fi

  - |
    if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then
      echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    else
      composer require lorenzo/multiple-iterator=~1.0
    fi
  - if [ "$RUN_PHPSTAN" = '1' ]; then composer require --dev phpstan/phpstan; fi

  - phpenv rehash
  - set +H

script:
  - if [ "$RUN_TESTS" = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - |
    if [ "$RUN_CS" = '1' ]; then
      vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=/Migrations/,/Seeds/ \
        ./config ./src ./tests ./plugins/*/*/config ./plugins/*/*/src ./plugins/*/*/tests
    fi
  - |
    if [ "$RUN_PHPSTAN" = '1' ]; then
      vendor/bin/phpstan analyse --no-progress src plugins/BEdita/API/src plugins/BEdita/Core/src
    fi

after_success:
  - if [ "$RUN_TESTS" = '1' ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
  slack:
    secure: TJ1c35YLgdYmIQRB58RKuEPDBN1XZYBjFI842lxa5Rl6FW/x+cJIYNCK3mU48/ULw9RfUla3bLf/oyffaj6pATRSK/jshiVKDU2Pq6yd/YV1aXpaMQLpzr8UJZk/KrG5cDAXhHW0U8O95sVpZm/pLwkNtk5tMPiuvJ35oVJyNuM=
