language: php

dist: trusty
sudo: required

services:
  - memcached
  - postgresql
  - redis-server

addons:
  mariadb: "10.1"
  postgresql: "9.6"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - RUN_TESTS=1

jobs:
  fast_finish: true

  include:
    - stage: minimal
      php: 5.6
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.0
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: minimal
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: minimal
      php: hhvm
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: RUN_CS=1 RUN_TESTS=0

    - stage: complete
      php: 5.6
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 5.6
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.1
      env: "DB=mysql DB_VERSION=5.6 db_dsn='mysql://root@localhost/bedita_test'"
      services:
        - memcached
        - mysql
        - redis-server
      addons: {}
    - stage: complete
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.5 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
      addons:
        postgresql: "9.5"
    - stage: complete
      php: hhvm
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.1
      env: RUN_PHPSTAN=1 RUN_TESTS=0

  allow_failures:
    - php: hhvm
    - php: 7.1
      env: RUN_PHPSTAN=1 RUN_TESTS=0

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
  - composer install --prefer-dist --no-interaction

  - if [ "$DB" = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE bedita_test;'; mysql -u root -e 'SHOW DATABASES;'; fi
  - if [ "$DB" = 'pgsql' ]; then psql -c 'CREATE DATABASE bedita_test;' -U postgres; fi

  - |
    if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then
      echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    else
      composer require lorenzo/multiple-iterator=~1.0
    fi
  - if [ "$RUN_PHPSTAN" = '1' ]; then composer require --dev phpstan/phpstan; fi

  - phpenv rehash
  - set +H

script:
  - if [ "$RUN_TESTS" = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - |
    if [ "$RUN_CS" = '1' ]; then
      vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=/Migrations/,/Seeds/ \
        ./config ./src ./tests ./plugins/*/*/config ./plugins/*/*/src ./plugins/*/*/tests
    fi
  - |
    if [ "$RUN_PHPSTAN" = '1' ]; then
      vendor/bin/phpstan analyse --no-progress src plugins/BEdita/API/src plugins/BEdita/Core/src
    fi

after_success:
  - if [ "$RUN_TESTS" = '1' ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
  slack:
    secure: TJ1c35YLgdYmIQRB58RKuEPDBN1XZYBjFI842lxa5Rl6FW/x+cJIYNCK3mU48/ULw9RfUla3bLf/oyffaj6pATRSK/jshiVKDU2Pq6yd/YV1aXpaMQLpzr8UJZk/KrG5cDAXhHW0U8O95sVpZm/pLwkNtk5tMPiuvJ35oVJyNuM=
