language: php

dist: trusty
sudo: required

services:
  - memcached
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - RUN_TESTS=1
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

jobs:
  fast_finish: true

  include:
    - stage: minimal
      php: 5.6
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.0
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: minimal
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.6 DB_POSTGIS=1 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: minimal
      php: hhvm
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: RUN_CS=1 RUN_TESTS=0

    - stage: complete
      php: 5.6
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 5.6
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.1
      env: "DB=mysql DB_VERSION=5.6 db_dsn='mysql://root@localhost/bedita_test'"
      services:
        - memcached
        - mysql
        - redis-server
      addons: {}
    - stage: complete
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.5 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
      addons:
        postgresql: "9.5"
    - stage: complete
      php: hhvm
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.1
      env: RUN_PHPSTAN=1 RUN_TESTS=0

    - stage: deploy
      php: 7.1
      env: RUN_TESTS=0
      addons: {}
      branches:
        only:
          - 4-cactus
      deploy:
        provider: heroku
        app: bedita4
        skip_cleanup: true
        run:
          - "bin/cake migrations migrate -p BEdita/Core"
          - "bin/cake cache clear_all"
        api_key:
          secure: c0PT+eED+fLi3azcpvSdlliMyVSgGFxYghdicy1KRBfalkdB0kUULYbhWSnU+SSryK4qEkkdfgNJvrFlcSOK/25s9hPB2B3iIhpxS2Zvmj49gKiUrrRfjvW6cJ8FvnYhIOuTdWIP4sjm3PkKh/5qoaU94zMhADi72BD6IpmVDpc=
#          secure: IoV+GK7hyX8/uWmuF7xuc+4SM0a9mCmKAckOTJ+LZj1zpzXRE8LkPXm5GnuYoO/ambRoZkORDwclrXMsloY3TJMFvJxG6UnOlKANBzwKankZK6vWv0O3Jni4TtbW48OShH7yj6iCS7uvwPFrA76c21qlLBp34QAFJO0y73lS+sY=
        on:
          all_branches: true
#          repo: bedita/bedita

  allow_failures:
    - env: RUN_PHPSTAN=1 RUN_TESTS=0

before_install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi

install:
  - composer install --prefer-dist --no-interaction
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then composer require lorenzo/multiple-iterator=~1.0; fi
  - if [ "$RUN_PHPSTAN" = '1' ]; then composer require --dev phpstan/phpstan; fi

before_script:
  # PHP Extensions
  - |
    if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then
      echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  - phpenv rehash
  - set +H

  # Databases
  - |
    if [ "$DB" = 'mysql' ] && [ "$DB_VERSION" = '5.7' ]; then
      echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
      wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
      sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
      sudo apt-get update -q
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" mysql-server
      sudo mysql_upgrade
    fi
  - if [ "$DB" = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE bedita_test;'; mysql -u root -e 'SHOW DATABASES;'; fi
  - if [ "$DB" = 'pgsql' ]; then psql -c 'CREATE DATABASE bedita_test;' -U postgres; fi
  - if [ "$DB" = 'pgsql' ] && [ "$DB_POSTGIS" = '1' ]; then psql -c 'CREATE EXTENSION postgis;' -U postgres; fi

  # CodeClimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - |
    if [ "$RUN_TESTS" = '1' ]; then
      vendor/bin/phpunit --coverage-clover=clover.xml
      if [ ! -z "$CC_TEST_REPORTER_ID" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        ./cc-test-reporter after-build --exit-code $?
      fi
    fi
  - |
    if [ "$RUN_CS" = '1' ]; then
      vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=/Migrations/,/Seeds/ \
        ./config ./src ./tests ./plugins/*/*/config ./plugins/*/*/src ./plugins/*/*/tests
    fi
  - |
    if [ "$RUN_PHPSTAN" = '1' ]; then
      vendor/bin/phpstan analyse --no-progress src plugins/BEdita/API/src plugins/BEdita/Core/src
    fi

after_success:
  - if [ "$RUN_TESTS" = '1' ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
  slack:
    secure: TJ1c35YLgdYmIQRB58RKuEPDBN1XZYBjFI842lxa5Rl6FW/x+cJIYNCK3mU48/ULw9RfUla3bLf/oyffaj6pATRSK/jshiVKDU2Pq6yd/YV1aXpaMQLpzr8UJZk/KrG5cDAXhHW0U8O95sVpZm/pLwkNtk5tMPiuvJ35oVJyNuM=

addons:
  code_climate:
    repo_token: e6fd85a6c11810e3c75def861e422a0c1e178ccff45d48e53e586d330bca0698
